config/routes.rb
Rails.application.routes.draw do
  # Show all of the restaurants at the root index
  get "/", to: "restaurants#index", as: "root"  

  # Static pages routes below 
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/help", to: "static_pages#help"
  ########

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/signup", to: "users#new"
  get "/logged_out", to: "static_pages#logged_out"

  resources :comments

  resources :users do
    member do
      get "/settings", to: "users#settings"
      get "/comments", to: "users#comments"
    end
  end
  resources :restaurants do
    member do
      put "upvote", to: "restaurants#upvote"
      put "downvote", to: "restaurants#downvote"
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :username, presence: true, length: { maximum: 40 }, uniqueness: { case_sensitive: true }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  acts_as_voter
  validates :password, presence: true, length: { minimum: 6 }

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a new token
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_token, User.digest(self.remember_token))
  end

  # Compares an encrypted remember token with a specific cookie
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user and removes all cookies associated with them
  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  helper_method :sort_column, :sort_direction

  def new
    @user = User.new
  end
  
  def show
    if !logged_in? || current_user.id != params[:id].to_i
      flash[:danger] = "You're not authorized to access this page."
      redirect_to root_path
    end
    @user = User.find params[:id]
    @restaurants = Restaurant.order(sort_column + " " + sort_direction).where(user_id: @user.id).paginate(:page => params[:page], :per_page => 10)
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = "Thanks for signing up for Waitlist!"
      log_in @user
      redirect_to @user
    else
      flash[:danger] = "Uh oh, something went wrong. Please read the error messages and try again."
      render 'new'
    end
  end

  # Settings
  def settings
    if !logged_in? || current_user.id != params[:id].to_i
      flash[:danger] = "You're not authorized to view this page."
      redirect_to root_path
    end
    @user = User.find params[:id]
  end

  # User can view their own comments
  def comments
    if current_user.nil? then redirect_to root_path end
    # SQL query to find all of the restaurants that the current user has 
    # made a comment on.
    @restaurants = Restaurant.find_by_sql "SELECT restaurants.id, name FROM restaurants JOIN comments ON (comments.restaurant_id = restaurants.id AND comments.user_id = #{params[:id]}) GROUP BY restaurants.name, restaurants.id"
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

    # Helper method for dynamic sorting of restaurants. Default sorting method is by name of the Restaurant.
    def sort_column
      Restaurant.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end

    # Helper method for dynamic sorting of restaurants.
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
    
end

app/views/users/_restaurant_list.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<table class="pretty">
  <tr class="header">
    <td><%= sortable "name" %></td>
    <td><%= sortable "wait" %></td>
    <td><%= sortable "updated_at" %></td>
    <td>Upvotes</td>
    <td>Downvotes</td>
  </tr>
  <% @restaurants.each do |restaurant| %>
    <tr>
      <td><%= link_to restaurant.name, restaurant %></td>
      <td><%= restaurant.wait %></td>
      <td><%= restaurant.updated_at %></td>
      <td><%= restaurant.get_upvotes.size %></td>
      <td><%= restaurant.get_downvotes.size %></td>
    </tr>
  <% end %>
</table>
<%= will_paginate @restaurants %>

app/views/users/comments.html.erb
<div class="center jumbotron">
  <h3>Your comments are below</h3>
  <% @restaurants.each do |restaurant| %>
    <% comments = Comment.where restaurant_id: restaurant.id %>
    <h4>For <%= link_to "#{restaurant.name}", restaurant_path(restaurant) %></h4>
    <% comments.each do |comment| %>
      <div class="comment">
        <%= comment.content %> <%= link_to "View", comment_path(comment), class: "btn btn-primary"%> <%= link_to "Edit", edit_comment_path(comment), class: "btn btn-primary" %> 
      </div>
    <% end %>
  <% end %>
    
</div>

app/views/users/new.html.erb
<div class="center jumbotron" %>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user) do |f| %>
        <%= render "shared/error_messages" %>

        <%= f.label :username %>
        <%= f.text_field :username, class: "form-control" %>

        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control" %>

        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>

        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: "form-control" %>

        <%= f.submit "Sign up!", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/settings.html.erb
<div class="center jumbotron">

  We don't have any settings yet but we will in the future!
  
</div>

app/views/users/show.html.erb
<div class="center jumbotron">
  <h1>Hello <%= @user.username %>!</h1>
  This is your user page. You current have <strong><%= if @user.reputation then @user.reputation else 0 end %> reputation</strong>. 
  <br>
  <%= link_to "View your comments.", comments_user_path(@user), class: "btn btn-primary" %>
  
  <% if !@restaurants.empty? %>
    <h2>Here is some info for the restaurants that you have posted about.</h2>

    <%= form_tag restaurants_path, :method => 'get', :id => "restaurant_search" do %>
      <p>
        <%= text_field_tag :search, params[:search], placeholder: "Enter a restaurant..." %>
        <%= submit_tag "Search", { :name => nil, class: "btn btn-primary" } %>
    <% end %>
        <div id="restaurants"><%= render "restaurant_list" %></div>
  <% else %>
    <h2>Doesn't look like you have any restaurants. <%= link_to "Post some!", new_restaurant_path %></h2>
  <% end %>
</div>

app/views/users/show.js.erb
$("#restaurants").html("<%= j(render "restaurant_list") %>");