config/routes.rb
Rails.application.routes.draw do
  # Show all of the restaurants at the root index
  get "/", to: "restaurants#index", as: "root"  

  # Static pages routes below 
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/help", to: "static_pages#help"
  ########

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/signup", to: "users#new"
  get "/logged_out", to: "static_pages#logged_out"

  resources :comments

  resources :users do
    member do
      get "/settings", to: "users#settings"
      get "/comments", to: "users#comments"
    end
  end
  resources :restaurants do
    member do
      put "upvote", to: "restaurants#upvote"
      put "downvote", to: "restaurants#downvote"
    end
  end
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  before_save { self.unique_name = name.downcase }
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :wait, presence: true, numericality: { greater_than_or_equal_to: 0 } 
  validates :address, presence: true
  validates :state, presence: true
  validates :zip, presence: true
  acts_as_votable

  # Define a search method for dynamic search purposes
  def self.search(search)
    if search
      where("name LIKE ?", "%#{search}%")
    else
      all
    end
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  helper_method :sort_column, :sort_direction

  def index
    @restaurants = Restaurant.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 10, :page => params[:page])
  end

  def show
    begin
      @restaurant = Restaurant.find(params[:id])
      @comments = Comment.where restaurant_id: params[:id]
      @comment = Comment.new
    rescue
      p "Being rescued"
      redirect_to restaurants_path
    end
  end
  
  def new
    if !current_user then redirect_to root_path end
    @user = current_user
    @restaurant = Restaurant.new
  end

  def edit
    @restaurant = Restaurant.find params[:id]
  end

  def update
    restaurant = Restaurant.find params[:id]
    
    # The following line will reset all of the votes that a wait time has.
    # The idea is that Users are voting on the wait time that has been
    # posted and not the quality of the Restaurant itself.
    restaurant.votes_for.destroy_all

    restaurant.update name: restaurant_params[:name], wait: restaurant_params[:wait] if restaurant_params
    redirect_to restaurant
  end

  def create
    @restaurant = Restaurant.new restaurant_params
    @restaurant.update user_id: current_user.id
    if @restaurant.save
      redirect_to root_path
    # Check for existence in database
    elsif Restaurant.exists? unique_name: @restaurant.name.downcase
      flash[:danger] = "That restaurant already exists in the database. Please update the wait time for this restaurant if you have the permission to or vote on the current wait time."
      redirect_to Restaurant.find_by unique_name: @restaurant.name.downcase
    elsif @restaurant.wait < 0
      flash[:danger] = "You can't post a restaurant with a negative wait time."
      redirect_to new_restaurant_path
    else
      flash[:danger] = "Uh oh, something went wrong. Try and make another restaurant!"
      redirect_to new_restaurant_path
    end
  end

  def destroy
    Restaurant.find(params[:id]).destroy
    redirect_to restaurants_path
  end
 
  # Handle upvotes
  def upvote
    @restaurant = Restaurant.find params[:id]
    current_user.likes @restaurant
    # Now update the reputation of the person that posted the most recent update to the Restaurant
    User.find(@restaurant.user_id).increment!(:reputation, 1)
    if request.xhr?
      render json: { upvote: true, count: @restaurant.get_upvotes.size, id: params[:id] }
    else
      redirect_to @restaurant
    end
  end
  
  # Handle downvotes
  def downvote
    @restaurant = Restaurant.find params[:id]
    current_user.dislikes @restaurant
    # Now update (by decrementing) the reputation of the user who most recently updated the wait time
    User.find(@restaurant.user_id).decrement!(:reputation, 1)
    if request.xhr?
      render json: { upvote: false, count: @restaurant.get_downvotes.size, id: params[:id] }
    else
      redirect_to @restaurant
    end
  end

  # Private methods below
  private
    def restaurant_params
      params.require(:restaurant).permit(:name, :wait, :address, :city, :state, :zip, :lat, :lng)
    end

    # Helper method for dynamic sorting of restaurants. Default sorting method is by name of the Restaurant.
    def sort_column
      Restaurant.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end

    # Helper method for dynamic sorting of restaurants.
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

end

app/views/restaurants/_restaurant_list.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<table class="pretty">
  <tr class="header">
    <td><%= sortable "name" %></td>
    <td><%= sortable "wait" %></td>
    <td><%= sortable "updated_at" %></td>
    <td>Upvotes</td>
    <td>Downvotes</td>
  </tr>
  <% @restaurants.each do |restaurant| %>
    <tr>
      <td><%= link_to restaurant.name, restaurant %></td>
      <td><%= restaurant.wait %></td>
      <td><%= restaurant.updated_at.getlocal.to_s[0..-7] %></td>
      <td><%= restaurant.get_upvotes.size %></td>
      <td><%= restaurant.get_downvotes.size %></td>
    </tr>
  <% end %>
</table>
<%= will_paginate @restaurants %>

app/views/restaurants/destroy.html.erb
<% if Restaurant.find(params[:id]) == nil then redirect_to restaurants_path end %>

app/views/restaurants/edit.html.erb
<div class="center jumbtron">
  <h1>You're editing the information for <%= @restaurant.name %> please do so kindly!</h1>
  <%= form_for(@restaurant) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :wait %>
    <%= f.number_field :wait, :step => 0.25 %>

    <%= f.submit "Update this restaurant!" %>
  <% end %>
</div>

app/views/restaurants/index.html.erb
<div class="center jumbotron"> 
  <h1>Current wait times</h1>
  <%= form_tag restaurants_path, :method => 'get', :id => "restaurant_search" do %>
    <p>
    <%= text_field_tag :search, params[:search], :placeholder => "Enter a restaurant..." %>
      <%= submit_tag "Search", { :name => nil, class: "btn btn-primary" } %>
  <% end %>
  <div id="restaurants"><%= render "restaurant_list" %></div>
  <br>
  <% if logged_in? %>
    <%= link_to "Make a new restaurant", new_restaurant_path, class: "btn btn-lg btn-primary" %>
  <% else %>
    <%= link_to "You must be logged in to post a wait time", login_path, class: "btn btn-lg btn-primary" %>
  <% end %>
</div>

app/views/restaurants/index.js.erb
$("#restaurants").html("<%= j(render 'restaurant_list') %>");

app/views/restaurants/new.html.erb
<div class="center jumbotron">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h3>Once you input the restaurant's name, the select menu below will be populated with addresses.</h3>
      <div>
        <select id="address_area">
          <option></option>
        </select>
      </div>
      <%= form_for(@restaurant) do |f| %>
        <%= render "shared/error_messages" %>

        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>

        <%= f.label :wait %>
        <%= f.number_field :wait, :step => 0.25, class: "form-control" %>

        <%= f.label :address %>
        <%= f.text_field :address, class: "form-control" %>

        <%= f.label :city %>
        <%= f.text_field :city, class: "form-control" %>

        <%= f.label :state %>
        <%= f.select :state, options_for_select(us_states), class: "form-control" %>

        <%= f.label :zip %>
        <%= f.text_field :zip, class: "form-control" %>

        <%= f.hidden_field :lat %>

        <%= f.hidden_field :lng %>

        <%= f.submit "Save this restaurant!", class: "btn btn-primary" %>
      <% end %>
      <div id="map"></div>
    </div>
  </div>
  <script type="text/javascript" charset="utf-8">
    var coords = new google.maps.LatLng(30.2777609, -97.7534014);
    var map = new google.maps.Map($("#map"), { center: coords, zoom: 13 });
    var service = new google.maps.places.PlacesService(map);
    $("#restaurant_name").change(function (e) {
      console.log(service.textSearch({ query: $("#restaurant_name").val(), location: coords, radius: 10000 }, function (res) {
        var select_tag = $("#address_area")[0];
        for (var i = 0; i < res.length; i++) {
          var option = document.createElement("option");
          option.innerHTML = res[i].formatted_address;
          option.id = res[i].geometry.location.A + "," + res[i].geometry.location.F
          console.log(res);
          select_tag.appendChild(option);
        }
      }));
    });
    
    // function to parse the formatted addresses that are returned from the Google
    // API call. Indices: 0 => address, 1 => city, 2=> state, 3 => zip.
    function parse_addr(address) {
      var info = address.split(",");
      var state = info[2].trim().split(" ")[0];
      info[3] = info[2].trim().split(" ")[1];
      info[2] = state;
      info[1] = info[1].trim();
      console.log("returning..." + info);
      return info;
    }

    $("#address_area").change(function (e) {
      var address_info = parse_addr($("#address_area").val());
      console.log(e);
      var lat_lng = $("option").filter(function () { return this.selected; })[0].id.split(",");
      // Set latitude and longitude
      $("#restaurant_lat").val(lat_lng[0]);
      $("#restaurant_lng").val(lat_lng[1]);
      // Set the address
      $("#restaurant_name").val($("#restaurant_name").val() + " " + address_info[0]);
      $("#restaurant_address").val(address_info[0]);
      $("#restaurant_city").val(address_info[1]);
      $("#restaurant_state").val(address_info[2]);
      $("#restaurant_zip").val(address_info[3]);
    }); 

  </script>
</div>

app/views/restaurants/show.html.erb
<div class="center jumbotron">
  <h2>You're looking at the information for <%= @restaurant.name %></h2>
  <p>
  <%= @restaurant.name %> currently has a wait of <%= @restaurant.wait %> minutes. And was posted by <%= User.find(@restaurant.user_id).username %>.
  <br>
  <span class="upvotes-count" data-id="<%= @restaurant.id %>"><%= @restaurant.get_upvotes.size %></span> upvotes. <span class="downvotes-count" data-id="<%= @restaurant.id %>"><%= @restaurant.get_downvotes.size %></span> downvotes.
  <% if logged_in? && current_user.id == @restaurant.user_id %>
    <br>
    <%= link_to "Delete this restaurant?", @restaurant, method: :delete, class: "btn btn-lg btn-primary" %>
    <%= link_to "Edit this restaurant's info?", edit_restaurant_path(@restaurant.id), class: "btn btn-lg btn-primary" %>
  <% else %>
    What do you think of this restaurant?
    <div id="button_area">
      <% if current_user && current_user.voted_for?(@restaurant) %> 
        <br>
        <h1>Thank you for voting on this restaurant.</h1>
      <% elsif current_user %>
        <%= link_to "I like it :)", upvote_restaurant_path(@restaurant.id), class: "btn btn-lg btn-primary", id: "upvote", method: :put, remote: true %>
        <%= link_to "I don't like it :(", downvote_restaurant_path(@restaurant.id), class: "btn btn-lg btn-primary", id: "downvote", method: :put, remote: true %>
      <% else %>
        <h1>You need to be logged in to cast votes on restaurant wait times.</h1>
      <% end %>
    </div>
  <% end %>
  <div id='map' style='height: 400px;'></div>
  <!-- Comment creation area -->
  <% if logged_in? %>
    <%= form_for(@comment) do |f| %>
      <%= f.label :content %>
      <%= f.text_area :content, placeholder: "Your comment goes here", class: "form-control" %>

      <%= f.hidden_field :user_id, value: current_user.id %>

      <%= f.hidden_field :restaurant_id, value: @restaurant.id %>
      
      <%= f.submit "Submit your comment!" %>
    <% end %>
  <% else %>
    <p>
    Please log in to make a comment.
  <% end %>
  <div id="comments">
    <% if !@comments.nil? %>
      <% @comments.each do |comment| %>
        <div class="comment">
          <h6><%= User.find(comment.user_id).username %> <%= if (logged_in? && comment.user_id == current_user.id) then link_to("Edit", edit_comment_path(comment), class: "btn btn-primary") end %></h6>
          <p>
            <%= comment.content %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
<script type="text/javascript" charset="utf-8">
  $("#upvote").on("ajax:success", function (status, data, xhr) {
    console.log("got data " + data.id);
    $("#upvote").blur();
    $(".upvotes-count[data-id=" + data.id + "]").text(data.count);
    $("#button_area").html("<h1>Thank you for voting on this restaurant.</h1>");
    return;
  });
  $("#downvote").on("ajax:success", function (status, data, xhr) {
    console.log("got data " + data.id);
    $("#downvote").blur();
    $(".downvotes-count[data-id=" + data.id + "]").text(data.count);
    $("#button_area").html("<h1>Thank you for voting on this restaurant.</h1>");
    return;
  });

  // Google maps code
  var handler = Gmaps.build("Google");
  var coords = Gmaps.Google.Builders.Bound.PRIMITIVES.latLngFromPosition([<%= @restaurant.lat %>, <%= @restaurant.lng %>]);
  handler.buildMap({ provider: { zoom: 13, maxZoom: 15, center: coords }, internal: { id: 'map' }}, function () {
    markers = handler.addMarkers([
        {
          "lat": <%= @restaurant.lat %>,
          "lng": <%= @restaurant.lng %>
        }
    ]);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });


</script>

app/views/restaurants/upvote.js.erb
// Handle an AJAX request from an upvote
console.log("Got here");